version: 2
updates:
  - package-ecosystem: "npm"  # See documentation for possible values
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
    groups:
      astro:
        patterns:
          - "astro"
          - "@astrojs/*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
